# Generated by Django 4.1.3 on 2022-11-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=30, unique=True)),
                ('student_number', models.CharField(max_length=30, unique=True)),
                ('fees_amount', models.IntegerField()),
            ],
        ),
    ]
