# Generated by Django 4.1.3 on 2022-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='student_number',
            field=models.CharField(max_length=30),
        ),
    ]
