# Generated by Django 4.1.3 on 2022-12-01 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.IntegerField(blank=True, default=0, editable=False, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
