# Generated by Django 4.1.3 on 2022-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Administrator', 'Admin'), ('Director', 'Director'), ('Teacher', 'Teacher')], max_length=13),
        ),
    ]
