# Generated by Django 4.1.3 on 2022-12-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('STU', 'Student'), ('ADM', 'Administrator'), ('DIR', 'Director'), ('TEA', 'Teacher')], max_length=13),
        ),
    ]
