# Generated by Django 4.1.3 on 2022-11-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_status',
            field=models.CharField(choices=[('SA', 'The lesson has been saved'), ('PN', 'The lesson request is pending'), ('BK', 'The lesson has been booked')], default='SA', max_length=30),
        ),
    ]
