# Generated by Django 4.1.3 on 2022-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('PAID', 'This invoices has been paid'), ('UNPAID', 'This invoice has not been paid'), ('PARTIALLY_PAID', 'This invoice has been partially paid')], default='UNPAID', max_length=30),
        ),
    ]
