# Generated by Django 4.1.3 on 2022-11-29 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_invoice_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amounts_need_to_pay',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice_reference_transaction',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Reference number must all be number and consist of - in between followed by at least three numbers', regex='^\\d*\\d-\\d\\d\\d\\d*$')]),
        ),
    ]
