# Generated by Django 4.1.3 on 2022-11-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_invoice_student_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='student_number',
            new_name='student_ID',
        ),
    ]
