# Generated by Django 4.1.3 on 2022-11-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_student_student_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
