# Generated by Django 4.1.3 on 2022-12-01 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_term_term_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term_number',
            field=models.IntegerField(editable=False, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
