# Generated by Django 4.1.3 on 2022-11-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_rename_student_number_invoice_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('PA', 'This invoices has not been paid'), ('UNPA', 'This invoice has been paid')], default='UNPA', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('INSTR', 'Learn To Play An Instrument'), ('TH', 'Instrument Music Theory'), ('PR', 'Instrument practice'), ('PERF', 'Performance Preparation')], default='INSTR', max_length=30),
        ),
    ]
