# Generated by Django 4.1.3 on 2022-12-01 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lesson_ID',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Lesson ID must all be number', regex='^\\d+$')]),
        ),
    ]
