# Generated by Django 4.1.3 on 2022-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_invoice_amounts_need_to_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Student transfer money from outside into their balance'), ('OUT', 'Student transfer money from balance into school account')], default='OUT', max_length=30),
        ),
    ]
