# Generated by Django 4.1.3 on 2022-12-01 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_invoice_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='lesson_ID',
            field=models.CharField(blank=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Lesson ID must all be number', regex='^\\d+$')]),
        ),
    ]
