# Generated by Django 4.1.3 on 2022-11-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_invoice_invoice_status_invoice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='type',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('PAID', 'This invoices has not been paid'), ('UNPAID', 'This invoice has been paid')], default='UNPAID', max_length=30),
        ),
    ]
