# Generated by Django 4.1.3 on 2022-11-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Administrator', 'Admin'), ('Director', 'Director')], default='Student', max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('PNOT', 'Prefer Not To Say')], default='PNOT', max_length=4),
        ),
    ]
