# Generated by Django 4.1.3 on 2022-12-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_invoice_invoice_status_alter_invoice_lesson_id'),
        ('lessons', '0006_alter_term_term_number'),
    ]

    operations = [
    ]
