# Generated by Django 4.1.3 on 2022-12-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_invoice_invoice_status_alter_invoice_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
