# Generated by Django 4.1.3 on 2022-11-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_student_role_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Administrator', 'Admin'), ('Director', 'Director')], max_length=13),
        ),
    ]
