# Generated by Django 4.1.3 on 2022-12-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_term_term_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='term',
            field=models.CharField(default='N/A', max_length=3),
        ),
    ]
