# Generated by Django 4.1.3 on 2022-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_invoice_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='student_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
